# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161021_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskallocation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taskallocation',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ManyToManyField(to='app.Employee'),
        ),
        migrations.DeleteModel(
            name='TaskAllocation',
        ),
    ]
