# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161022_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(to='app.Employee'),
        ),
    ]
