# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_signoff_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='signoff_by',
        ),
    ]
