# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161025_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
            preserve_default=False,
        ),
    ]
