# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161022_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='app.Employee'),
        ),
    ]
